server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name your_domain www.your_domain.com ;

    root /var/www/my-site/directory; 
    index index.html;

    location /{
    # This removes .html from the search bar. $1 acts as a variable
     if ($request_uri ~ ^/(.*)\.html(\?|$)) {
        return 302 /$1;
    }
        try_files $uri $uri.html $uri/ =404;

    }

    location /api{
        proxy_pass http://localhost:3000;
    }
}


